export 'package:solgis/projects/people/presentation/pages/personal/widgets/crear_personal_body.dart';
export 'package:solgis/projects/people/presentation/pages/personal/widgets/dni_register_crear_personal.dart';
export 'package:solgis/projects/people/presentation/pages/personal/widgets/dropdown_button2_personal.dart';
export 'package:solgis/projects/people/presentation/pages/personal/widgets/dropdown_button_personal.dart';
//export 'package:solgis/projects/people/presentation/pages/personal/widgets/crear_personal_body.dart';
export 'package:solgis/projects/people/presentation/pages/personal/widgets/habilitar_personal_body.dart';
export 'package:solgis/projects/people/presentation/pages/personal/widgets/image_card_crear_personal.dart';
export 'package:solgis/projects/people/presentation/pages/personal/widgets/image_created_widget.dart';
export 'package:solgis/projects/people/presentation/pages/personal/widgets/sexo_register_crear_personal.dart';